---
title: "Series Temporales"
author: "Armando Ocampo"

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Series Temporales

```{r librerias, echo=TRUE, message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(ggpubr)
```


```{r data, echo=TRUE}
covid_mexico <- readRDS('../data/covid_mexico.RDS')
```


```{r explorando, echo=TRUE}
min(covid_mexico$date)
max(covid_mexico$date)
summary(covid_mexico$date)
length(covid_mexico$date)
1310/365  #3.5 años
deltat(covid_mexico$date) # intervalo de fechas
```


```{r diferencia, echo=TRUE}
diferencia_casos <- diff(covid_mexico$total_cases) %>%
  na.omit()

head(diferencia_casos,20)
```


```{r grafico, echo=TRUE, warning=FALSE, message=FALSE}
ggplot(covid_mexico, aes(x = date, y = total_cases)) +
  geom_line()
```


```{r grafico2, echo=TRUE, warning=FALSE, message=FALSE}
ggplot(covid_mexico, aes(x = date, y = total_cases)) +
  geom_line() +
  geom_smooth()
```



```{r grafico3, echo=TRUE, warning=FALSE, message=FALSE}
ggplot(covid_mexico, aes(x = date, y = total_cases)) +
  geom_line() +
  geom_smooth() +
  xlab('Fecha') +
  ylab('Casos Totales') +
  theme_bw()
```

scale_x_date() para darle formato a la fecha

%d: Day as a number between 0 and 31

%a: Abbreviated weekday (e.g. “Tue”)

%A: Unabbreviated weekday (e.g. “Tuesday”)

%m: Month between 0 and 12

%b: Abbreviated month (e.g. “Jan”)

%B: Unabbreviated month (e.g. “January”)

%y: 2-digit year (e.g. “21”)

%Y: 4-digit year (e.g. “2021”)

%W: Week of the year between 0 and 52


```{r grafico4, echo=TRUE, message=FALSE, warning=FALSE}
ggplot(covid_mexico, aes(x = date, y = total_cases)) +
  geom_line() +
  geom_smooth() +
  xlab('Fecha') +
  ylab('Casos Totales') +
  scale_x_date(date_labels = '%b %Y') +
  theme_bw()
```


```{r grafico5, echo=TRUE, warning=FALSE, message=FALSE}
ggplot(covid_mexico, aes(x = date, y = total_cases)) +
  geom_line() +
  geom_smooth() +
  xlab('Fecha') +
  ylab('Casos Totales') +
  scale_x_date(date_labels = '%b %Y',
               date_breaks = '4 month') +
  theme_bw()
```


```{r filtrando, echo=TRUE}
min(covid_mexico$date)
max(covid_mexico$date)
```


```{r filtrando2, echo=TRUE}
covid_mexico %>%
  filter(date >= '2021-01-01',
         date <= '2021-12-31')
```






















